platanus/froggo

- app/observers/pull_request_observer.rb
- app/services/pull_request_relation_service.rb
- spec/observers/pull_request_observer_spec.rb
- spec/services/pull_request_relation_service_spec.rb
Cada vez que se creaban las relaciones de un PR (pull request), solo se creaban un tipo de relación (`merged_by` o `reviewer`). El problema estaba en que el método que creaba las relaciones de review (`creates_from_reviews`) borraba todas las relaciones del PR, no solamente las de tipo `reviewer`.
Se aprovecho de cambiar el comando por un servicio, ya que cada vez que hay un cambio en la información de merge de un PR o sus reviews se actualizaban todos los tipos de relaciones que tiene el PR. Estas relaciones son independientes, por lo que las separé.
- Cambié el comando `CreatePullRelation` por `PullRequestRelationService`.
> feat(pr-relations): change create pr relation command for a service

- app/controllers/home_controller.rb
- app/views/home/index.html.erb
- config/locales/en.yml
- config/locales/es-CL.yml
En la vista de Home no está identificando si el usuario ya se ha logueado con Github, por lo que siempre muestra el botón "Connect to Github" que hace el login. Esto genera un problema, porque se sobreescribe el token que se tenía antes por uno nuevo con permiso de usuario normal. Por lo tanto, si antes habías pedido permisos de Admin, habría que pedirlos nuevamente.
- En el controlador `HomeController` se verifica si el usuario está logueado.
- Botón de home redirige directamente a los dashboards si el usuario ya ha ingresado.
- Traducción para el botón de inicio.
> feat(home): change home btn text if user is already logged

- app/services/pull_request_relation_service.rb
- spec/services/pull_request_relation_service_spec.rb
No se esta asignado la fecha de actualización a las relaciones de tipo `merged_by` de los pull requests. Se le asignará la fecha `gh_merged_at` que es cuando se realizó el merge en Github.
- Asignar la fecha de merge de un pull request a la relación.
- Agregar un test para que valide que `PullRequestRelation` de tipo `merged_by` se haya creado correctamente.
> fix(pr-relations): fix merge relations date to use merged_at of the pr

- app/services/github_pull_request_review_service.rb
- app/services/github_pull_request_service.rb
- app/services/repository_tracking_service.rb
- spec/services/github_pull_request_review_service_spec.rb
- spec/services/github_pull_request_service_spec.rb
El proceso de *tracking* de un repositorio no para si es que este ha cambiado su estado a *no trackeado* Se agregó un validador que refresca los datos del repositorio y consulta si sigue estando *trackeado*.
- Agregado un validador de `repository.reload.tracked` que actualiza los datos del repositorio y verifica que siga estando *trackeado*.
> Check track on create

- app/models/pull_request.rb
- app/models/pull_request_review.rb
- app/observers/pull_request_observer.rb
- app/observers/pull_request_review_observer.rb
- app/services/pull_request_relation_service.rb
- db/migrate/20180424180910_remove_column_last_pr_reviews_modification.rb
- db/schema.rb
- spec/models/pull_request_review_spec.rb
- spec/observers/pull_request_observer_spec.rb
- spec/observers/pull_request_review_observer_spec.rb
No se estaban creando todas las relaciones correspondientes a los reviews existentes.
Una hipótesis de por qué puede pasar es que `PullRequestObserver` no se estaba llamando a la creación de relaciones cuando correspondía. Este observer crea las relaciones de review solamente si el atributo `last_pull_req_review_modification` ha cambiado y este atributo es actualizado cada vez que se  asigna un nuevo review al pull requests. Como los reviews son creados muy rápido, puede que la fecha sea la misma y se hayan creado varios reviews seguidos.
Cambiamos el gatillador a un observer de la misma clase `PullRequestReview` para que actualice las `PullRequestRelation` cada vez que se guardan.
* Se eliminó el atributo `last_pull_req_review_modification`.
* Se saco la actualización de las relaciones …
> Review relation on create

- app/values/correlation_matrix.rb
Cuando se obtiene los puntajes de la matriz, en los puntajes de las diagonales faltaba filtrar los pull requests que el usuario era dueño `target_user_id`.
> fix(correlation-matrix): fix alone score to use owner prs

- spec/values/correlation_matrix_spec.rb
En el archivo: _spec/values/correlation_matrix_spec.rben_, el test `'should assign alone score correctly'` no estaba probando lo que realmente debía. Faltaba añadir los usuarios a la organización correspondiente para que la matriz los tome en cuenta y los agregue.
Además se hizo un refactor del test `'should place current user first'`, estaba en un contexto separado siendo que el contexto debiera ser el mismo usado al probar cuando se inicializa la matriz.
> Fix test for Correlation Matrix

- app/services/github_pull_request_service.rb
- spec/services/github_pull_request_service_spec.rb
`ImportPullRequestJob` se caía cuando había un PR desde un fork, ya que [aquí](https://github.com/platanus/froggo/blob/6fedc64dd5862f873e05911d968242f136a0417a/app/services/github_pull_request_service.rb#L67) antes se sacaba el nombre del repo desde la PR, lo que correspondía al repo fork, no el original.
Se probó en staging y funciona. En la imágen `testorg225/testrepo3 = repository.full_name` y `difernandez/testrepo3 = github_pull_request.head.repo.full_name`
> fix(github-pr-service): get repo name from repository instead of PR

- app/controllers/github_users_controller.rb
- app/models/github_user.rb
- app/values/github_session.rb
- spec/values/github_session_spec.rb
Si un miembro de una organización se mete a ver el perfil de otro miembro de la misma organización, entonces _sí_ debería poder saber si este otro miembro es o no miembro de la organización.
[Octokit::Client#organizations](http://octokit.github.io/octokit.rb/Octokit/Client/Organizations.html#organizations-instance_method) sólo devuelve las organizaciones para las que el usuario ha hecho pública su membresía, independiente de si el cliente representa un miembro de la misma organización.
Ahora se ocupa el conocimiento que se tiene en la db para pedir las organizaciones de un usuario.
> Determinar membresía de organización para obtener equipos a través de la db

- app/javascript/components/teams-dropdown.vue
- yarn.lock
Para cada perfil, se recuerda el último equipo (en local storage) que fue seleccionado. Si se vuelve a cargar ese perfil, entonces ese equipo viene seleccionado.
> Recordar el último equipo seleccionado en el perfil del usuario

- app/controllers/concerns/github_authenticable.rb
- app/controllers/github_users_controller.rb
- app/controllers/home_controller.rb
- app/controllers/organizations_controller.rb
- app/values/github_session.rb
- app/views/home/index.html.erb
- app/views/partials/_header.html.erb
- spec/controllers/home_controller_spec.rb
- spec/controllers/organizations_controller_spec.rb
- spec/values/github_session_spec.rb
También le hice un pequeño refactor a `github_session`para evitar las llamadas a `set_user` y `set_organization`. Además, ahora se persiste el usuario en `GithubUsers` cuando se loggea.
> Redirigir a la página de perfil del usuario si ya está loggeado

- app/controllers/github_auth_controller.rb
- app/controllers/home_controller.rb
- app/views/home/index.html.erb
- spec/controllers/github_auth_controller_spec.rb
- spec/controllers/home_controller_spec.rb
Cuando un usuario hace login entra a la pagina de su perfil en vez del dashboard. Si ya estaba logueado se redirige directamente al perfil, sin pasar por el home.
> feat(home): set profile page as default landing page

- app/commands/get_review_recommendations.rb
- spec/commands/get_review_recommendations_spec.rb
Se arregla el cálculo de recomendaciones para que considere las requests que el usuario ha hecho, en vez de las que el usuario ha recibido.
> fix(recommendations): correctly compute recommendations

- app/views/partials/_header.html.erb
Header arreglado para que muestre la foto de perfil del usuario logeado en vez de la del usuario de la pagina de perfil en que se encuentra.
> fix(header): show authenticated user's avatar in header

- app/commands/get_review_recommendations.rb
- spec/commands/get_review_recommendations_spec.rb
Al calcular las recomendaciones para los usuarios, se asigna un punto por request hecha en el último mes, y 3 puntos por request hecha en la última semana.
> Agregar peso a los puntajes de los request según fecha

- app/views/layouts/_google_analytics.html.erb
- app/views/layouts/application.html.erb
Se agrega google analytics para trackear los ingresos a los perfiles de los usuarios.
> Agregar google analytics

- app/assets/stylesheets/app/profile.scss
- app/views/github_users/_profile_card.html.erb
- config/locales/es-CL.yml
- Eliminar el puntaje de la vista del perfil de usuario.
- Información del usuario y recomendaciones en una "misma fila". Si la información del usuario está arriba de las recomendaciones le quita importancia, hay que tratar que se note que las recomendaciones son lo principal de la vista.
- Mensaje a los usuarios sin recomendaciones por no tener equipos
> feat(user-profile): delete scores from profile and highlight recommendations

- app/services/github_pull_request_service.rb
- spec/services/github_pull_request_service_spec.rb
Al revisar si el payload de la api de Github incluye el field `requested_reviewers` se buscaba la key como string, pero se debe buscar como símbolo.
> fix(requested-reviewers): fix requested_reviewers presence verification

- app/services/github_pull_request_service.rb
- spec/services/github_pull_request_service_spec.rb
Había un error al intentar acceder a la información de los usuarios a los que se les solicita revisar un PR en el payload de la api de Github. Se estaba intentando recuperar la información directamente en el field `requested_reviewers`, pero dentro de este hay que acceder adicionalmente al field `users`.
> fix(requested-reviewers): fix error when reading github api payload

- app/services/github_pull_request_review_service.rb
- app/services/github_pull_request_service.rb
- spec/services/github_pull_request_review_service_spec.rb
- spec/services/github_pull_request_service_spec.rb
El payload se estaba leyendo de manera incorrecta, el field `requested_reviewer` está en singular, no en plural. Además, se chequea que la acción del evento de Github sea `review_requested` en vez de revisar que exista el field `requested_reviewer`, para determinar si se lleva a cabo o no el método. `add_requested_reviewers_to_pull_request`.
También se cambia la forma de obtener los ids de los miembros del equipo para obtener las recomendaciones de froggo, usando el flag `is_member_of_default_team` de `OrganizationMembership`, en vez de intentar obtenerlos a través del cliente de la api de Github.  
Por último, se usa el `default_team_id` para determinar el equipo en el que se buscan las recomendaciones, en vez de una variable hardcodeada.
> fix(requested_reviewers): change requested_reviewer field reading

- app/admin/github_user.rb
Se agrega una tabla con las organizaciones del usuario, que incluye un flag que indica si el usuario pertenece o no al equipo default de esa organización.
> feat(admin): show user organizations

- app/views/organizations/_dashboard_table.html.erb
Se arregla el tamaño de los usuarios
> fix(organization-dashboard): fix user images sizes

- app/commands/create_organization.rb
- app/commands/github/process_membership_event.rb
- app/commands/process_webhook_event.rb
- app/controllers/api/v1/organizations_controller.rb
- app/controllers/organizations_controller.rb
- app/services/github/organization_webhook_service.rb
- spec/commands/create_organization_spec.rb
- spec/commands/github/process_membership_event_spec.rb
- spec/commands/process_webhook_event_spec.rb
- spec/services/github/organization_webhook_service_spec.rb
Se integra el uso de `organization_webhooks` de Github, creándolos al inicializar o actualizar (en este caso solo si el webhook de la organización actualizada no existe todavía) una aplicación en froggo. Este webhook permite a Github avisar cuando se elimina o agrega un miembro a un equipo de la organización.
Utilizando este webhook, se refleja en la base de datos de froggo cuando en Github se agrega o elimina un miembro de la organización al equipo seleccionado como default en froggo.
> Membership webhook

- app/controllers/organizations_controller.rb
- app/views/organizations/_settings_content.html.erb
- config/locales/en.yml
- config/locales/es-CL.yml
Había un bug al crear una organización nueva, que al no tener `default_team_id` causaba un error al intentar entrar a las settings de la organización. 
Se corrige el bug, manejando el caso en que una organización no tiene equipo default para que no se calculen los valores de las estadísticas de la organización y se le solicita al admin que seleccione un equipo.
> Fix Bug: settings page doesn't crash when the organization has no default team selected

- app/commands/get_recommendations.rb
- app/controllers/api/v1/github_users_controller.rb
- app/controllers/slack/commands_controller.rb
- app/controllers/slack/events_controller.rb
- app/services/slack_commands_service.rb
- config/locales/en.yml
- config/locales/es-CL.yml
- config/routes.rb
- spec/commands/get_recommendations_spec.rb
- spec/services/slack_commands_service_spec.rb
Se recomienda por Slack a quienes asignar su próximo PR, a través del slash command `next_pr <gihub_username> <organization_name>`. 
1) Se crea el comando `GetRecommendations` que por ahora funciona como un wrapper del comando `GetReviewRecommendations`. La diferencia es que recibe el usario y la organización, en vez del `id` del usario y el `id` de todos los demás usuarios con los que se quiere comparar; y entrega las recomandaciones según el team default de la organización. La idea es que el nuevo comando reemplace al antiguo más adelante. 
2) Para que las recomendaciones sean las mismas en la aplicación y en slack, se le deben pasar los ids de usuarios ordenados a `GetReviewRecomendations` para manejar los casos de empate.
3) Se crea un servicio `SlackCommands` que maneja las …
> feat(slack-integration): recommend next PR by Slack

- app/services/slack_commands_service.rb
- config/locales/en.yml
- config/locales/es-CL.yml
- spec/services/slack_commands_service_spec.rb
Se agrega el manejo de un nuevo comando `/summary` que retorna las estadísticas de obediencia del usuario.
Además se cambia `messages.slack.wrong_params` por `messages.slack.next_pr_wrong_params` para diferenciar el caso en que los parámetros son incorrectos para el slash command `/next_pr` y `/summary`.
**Tests**
1. Se revisan los casos de error en que:
- número de parámetros adicionales a slash command es incorrecto
- usuario u organización no existen
- usuario no pertenence a la organización o su team default
2. Se cambia el uso de `before do` por `let!` para `:organization_membership`
> feat(slack): send summary of user statistics with /summary command

- app/services/github_user_service.rb
- spec/services/github_user_service_spec.rb
Arreglado que cuando los usuarios eran creados antes de que se logearan a froggo por primera vez
(ej: cuando aparecen en un PR), quedaban permanentemente sin nombre en la BD.
Ahora los nombres se irán guardando a medida que los usuarios se vayan logeando.
> fix(github_service): fixed user names not being stored.

- app/models/pull_request_review.rb
- app/services/github_pull_request_review_service.rb
- db/migrate/20200825200237_add_approved_at_to_pull_request_review.rb
- db/schema.rb
- spec/services/github_pull_request_review_service_spec.rb
Este pr agrega el atributo de approved_at a PullRequestReview y modifica el servicio llamado al recibir un Webhook de _pull request review_, con el objetivo de guardar el timestamp en que cada usuario revisor de un pull request aprueba los cambios de dicho pr, para luego ocupar esta información en las métricas temporales.
> Profile metrics

- app/assets/stylesheets/app/app.scss
- app/assets/stylesheets/app/froggo_teams.scss
- app/assets/stylesheets/app/header.scss
- app/assets/stylesheets/application.scss
- app/controllers/api/v1/froggo_teams_controller.rb
- app/controllers/froggo_teams_controller.rb
- app/javascript/components/froggo-team-form.vue
- app/javascript/components/froggo-team-show.vue
- app/javascript/components/froggo-teams-list.vue
- app/javascript/mixins/showMessageMixin.js
- app/javascript/packs/application.js
- app/javascript/store/modules/froggo_team/actions.js
- app/views/froggo_teams/_froggo_teams_list.html.erb
- app/views/froggo_teams/index.html.erb
- app/views/froggo_teams/show.html.erb
- app/views/partials/_header.html.erb
- config/locales/en.yml
- config/locales/es-CL.yml
- config/routes.rb
- package.json
- spec/controllers/api/v1/froggo_teams_controller_spec.rb
- yarn.lock
el objetivo de este PR es agregar en el fornt-end las funcionalidades para ver todos los froggo-teams (index), ver uno en particular (show) y borrar en caso de ser necesario. (los froggo-teams se refiere a los equipos locales que se pueden armar en froggo).
Para esto se crearon las rutas para index y show y la respectiva vista de cada una. Además se agregó un botón en la barra de navegación para que el usuario pudiera acceder a sus equipos y a partir de ahí pudiera decidir si crear uno nuevo, ver alguno en particular o borrarlo.
Este PR no considera editar, es el último que me está faltando :)
> Froggo teams form

- app/controllers/organizations_controller.rb
- app/models/github_user.rb
- app/views/organizations/_card_header.html.erb
- spec/controllers/organizations_controller_spec.rb
En este PR se integran los equipos locales de froggo junto con los de github. Antes solo al usuario le aparecían los equipos de github en el dropdown y podía seleccionar solo esos. Ahora la idea es que también le aparezcan los equipos locales y tambien pueda hacer click sobre ellos y se despliegue su respectivo dashboard
> feat(FroggoTeams): add froggo teams to teams dashboard

- app/assets/stylesheets/app/froggo_teams.scss
- app/javascript/components/froggo-teams-list.vue
- app/javascript/mixins/showMessageMixin.js
- app/views/froggo_teams/_empty.html.erb
- app/views/froggo_teams/_froggo_teams_list.html.erb
- config/locales/en.yml
- config/locales/es-CL.yml
En este PR moví los mensajes de alerta a la esquina derecha de la pantalla, agregué una view para cuando un usuario no tiene organizaciones y cambié la forma en que se muestran los títulos de los equipos en el froggo-teams-list
> Froggo teams style details

- app/services/github_pull_request_review_service.rb
- db/data/20200909203445_fix_approved_at_values_for_pull_request_reviews.rb
- db/data_schema.rb
- db/schema.rb
El servicio de manejo de webhooks fallaba en el caso de crear un PullRequestReview record con información de approved_at, ya que el timestamp de approved_at era 1 segundo previo al timestamp de creación del PullRequestReview record. Esto generaba resultados negativos en las métricas de perfil.
Este pr aborda este caso y realiza un data migration para los datos ya registrados
> Fix pull request reviews approved at

- app/models/pull_request.rb
- app/services/github_pull_request_service.rb
- db/migrate/20200910192320_add_last_change_to_pull_request.rb
- db/schema.rb
- spec/factories/pull_requests.rb
En este pr se edita el servicio que maneja los webhooks de pull request, con la intención de guardar el timestamp del último cambio realizado por el autor.
Esta adición será usada para obtener la métrica de "número de pull requests que son editados y mergeados sin una posterior aprobación"
> Unchecked merges metrics

- app/controllers/api/v1/froggo_teams_controller.rb
- app/controllers/api/v1/organizations_controller.rb
- app/controllers/github_users_controller.rb
- app/controllers/organizations_controller.rb
- app/javascript/components/teams-dropdown.vue
- app/javascript/store/modules/admin/actions.js
- app/models/froggo_team.rb
- app/models/organization.rb
- app/observers/froggo_team_observer.rb
- app/services/github_org_membership_service.rb
- db/data/20200921172413_nullify_default_team_id.rb
- db/data_schema.rb
- spec/observers/froggo_team_observer_spec.rb
- spec/services/github_org_membership_service_spec.rb
hasta ahora en froggo existen 2 tipos de equipos, los locales (froggoTeams) y los de github y ambos se muestran a los usuarios. La idea de este PR es que desde ahora solo se muestren equipos de froggo, y dejar de depender de los equipos de github.
Esto significa que por ejemplo desde ahora las organizaciones ya no podrán tener equipos de github como default team, sino que tendrán que elegir un froggoTeam como equipo por default.
> show only Froggo Teams 

- app/javascript/components/profile/metrics-handler.vue
Cebido a que las entradas de unfilteredData poseen también un label, la condición anterior nunca se cumplía. Ahora se itera solamente por las métricas númericas.
> fix(user-metrics): update data trimming condition for all zero entries

- app/assets/stylesheets/app/app.scss
- app/assets/stylesheets/app/froggo_teams.scss
- app/assets/stylesheets/app/switch.scss
- app/controllers/api/v1/froggo_teams_controller.rb
- app/controllers/froggo_teams_controller.rb
- app/javascript/components/froggo-team-show.vue
- app/javascript/locales/en.js
- app/javascript/locales/es.js
- app/javascript/store/modules/froggo_team/actions.js
- app/models/froggo_team_membership.rb
- app/views/froggo_teams/show.html.erb
- db/data/20200923161151_add_true_value_to_is_member_active.rb
- db/data_schema.rb
- db/migrate/20200923140921_add_member_active_to_froggo_team_memberships.rb
- db/schema.rb
Antes el path de froggo teams show, mostraba una vista con el equipo froggo team  (sus miembros y características) y además se podía editar el equipo desde ahí mismo. Ahora la idea es que existan 2 vistas separadas ... una que sea show y otra que sea edit. La idea es que show solo muestre al equipo y se puedan activar y desactivar sus miembros, y que edit permita editar las características del equipo como el nombre, miembros, etc.
En este PR está el nuevo "show", que por una parte ya no incluye los métodos de edición que antes incluía y por otra agrega una nueva funcionalidad que es la de activar o desactivar miembros del equipo, a través de un botón switch. La idea de esto último es que para cada equipo se pueda setear si un miembro está o no activo (por ejemplo se debería poder …
> Update froggo teams show

- app/controllers/froggo_teams_controller.rb
- app/javascript/components/froggo-team-edit.vue
- app/javascript/packs/application.js
- app/views/froggo_teams/edit.html.erb
- config/routes.rb
Este PR crea la vista para froggo_teams edit. En esta vista la idea es que el usuario pueda cambiar el nombre del equipo, agregar miembros, eliminar miembros o eliminar al equipo completo. (se que le falta cariño al diseño 😅  jajajja pero más adelante está contemplado mejorar eso).
Esta es la vista:
> Froggo teams edit

- Gemfile
- Gemfile.lock
- app/commands/compute_color_score.rb
- app/commands/get_review_recommendations.rb
- app/controllers/api/v1/github_users_controller.rb
- app/javascript/components/froggo-team-show.vue
- app/models/froggo_team_membership.rb
- db/migrate/20200929135242_add_last_deactivation_date_to_froggo_team_memberships.rb
- db/migrate/20200929135252_add_last_activation_date_to_froggo_team_memberships.rb
- db/schema.rb
- spec/models/froggo_team_membership_spec.rb
La idea de este PR es implementar la activación y desactivación de miembros de un equipo, y calcular las recomendaciones considerando la actividad de los usuarios. Para ello, se definieron dos cosas principalmente. La primera es que cuando un usuario esté inactivo, este no le aparezca en las recomendaciones de sus compañeros de equipo. Y la segunda es evitar que cuando un usuario que haya estado desactivado varios días se vuelva activar, le llegue un gran número de PR. Esto último se hizo utilizando una nueva fórmula para calcular el puntaje de cada usuario, que ahora solo considera los días en que el usuario ha estado activo.
> Froggo teams active members

- app/views/pull_requests/index.html.erb
En frog se tenía el bug de que se de rails se entregaba un string pero Vue lo recibía como un método por lo que no cargaba la página.
El error se veía así:
Para arreglarlo se eliminaron los ":" que hacía que Vue pensara que era un método y se quitó el camelizeKeys para que no pensara que era una clase. Ahora funciona correctamente.
> fix(index.html.erb): fixed bug that treated string as method

- app/assets/stylesheets/app/card.scss
- app/views/kaminari/_gap.html.erb
- app/views/kaminari/_paginator.html.erb
Arreglo muy chico de loa paginación. Donde sale Truncate se cambió para que salgan "..." y además se dio margen con el display abajo de la paginación:
Quedando así:
> fix(_gap.html.erb): fixed bug of pagination

- app/assets/stylesheets/app/profile.scss
- app/controllers/organizations_controller.rb
- app/javascript/components/organization-matrix-head.vue
- app/javascript/locales/en.js
- app/javascript/locales/es.js
- app/javascript/packs/application.js
- app/views/organizations/_dashboard_table.html.erb
La idea de este PR es que en la vista de organizaciones de froggo, en el dashboard, al poner el mouse sobre algún usuario muestre su nombre, su puntaje, y los días que ha estado inactivo o de vacaciones.
Para eso se tuvo que construir un nuevo componente en vue: organization-matrix-head, y a cada imagen implementar la clase tooltip.
Aquí una imagen del antes y el después:
Antes:
Después
> Froggo organization dashboard users

- app/commands/compute_color_score.rb
- app/controllers/api/v1/froggo_teams_controller.rb
- app/controllers/froggo_teams_controller.rb
- app/javascript/components/froggo-team-show.vue
- app/javascript/store/modules/froggo_team/actions.js
- app/models/froggo_team_membership.rb
- db/data/20201006144402_add_value_to_assignment_percentage.rb
- db/data_schema.rb
- db/migrate/20201006141955_add_assignment_percentage_to_froggo_team_memberships.rb
- db/schema.rb
- spec/models/froggo_team_membership_spec.rb
La idea de este PR es implementar que las personas que son miembros de un equipo de Froggo, se puedan asignar un % de asignación de PRs. Por ejemplo ... si estoy trabajando en un proyecto, y me gustaría que me envíen solo el 50% de los pr que les envían al resto de mis compañeros, lo puedo setear.
Para eso se agregó la columna assignment_percentage :)
> Froggo team members percentage

- app/javascript/components/organizations-dropdown.vue
- app/javascript/components/profile/recommendations.vue
- app/javascript/locales/en.js
- app/javascript/locales/es.js
Este PR es para agregar al perfil de froggo un mensaje cuando el usuario elija una organización en la cual aún no es miembro de ningún equipo.
> No teams message

- app/assets/stylesheets/app/dropdown.scss
- app/javascript/components/percentage-dropdown.vue
- app/javascript/locales/en.js
- app/javascript/locales/es.js
En este PR se agrega un tooltip sobre el % de los usuarios que tienen menos de 100% de asignación de PRs (se muestra un mensaje cuando el usuario pone su mouse sobre el % actual).
> Percentage tooltip

- app/javascript/locales/en.js
- app/javascript/locales/es.js
- app/views/github_users/_profile_card.html.erb
- config/locales/en.yml
- config/locales/es-CL.yml
Este PR borra una doble verificación que se hacía para saber si el usuario no tiene teams y arregla los mensajes que se muestran.
> Fix no teams message

- app/assets/stylesheets/app/card.scss
- app/javascript/locales/en.js
- app/javascript/locales/es.js
- app/views/pull_requests/index.html.erb
El feed se presentan todas las pull requests que hay en platanus. Esto claramente es un problema por las decenas que se hacen diarias y se dificulta la búsqueda de un PR en específico. Para esto se decidió hacer filtros.
Antes de esta PR, habían dos filtros de texto para las pull requests. El primero es según el nombre del proyecto y el segundo según el nombre del creador de la PR.
Son 6 filtros que se veían así:
Y ahora se hicieron cambios para que se vieran así:
> design(index.html): better distribution

- app/javascript/components/profile/relations.vue
Actualmente se puede ver más información en la vista de organizaciones cuando uno se sitúa sobre una imagen de alguien del equipo (en este caso Andrés):
Se quiso hacer lo mismo para el perfil que antes no se podía y ahora quedó igual:
> feat(relations.vue): added information of other users on profile

- .circleci/config.yml
- app/javascript/components/organization-matrix-head.vue
Actualmente se puede ver más información en la vista de organizaciones cuando uno se sitúa sobre una imagen de alguien del equipo (en este caso Raimundo), pero el Puntaje se puede ver gigante con todos los floats:
Es por esto que aquí simplemente se aproxima al segundo decimal ese Puntaje
> fix(organization-matrix-head.vue): approximated scores to the second decimal

- app/controllers/home_controller.rb
- app/views/froggo_teams/edit.html.erb
- app/views/froggo_teams/index.html.erb
- app/views/froggo_teams/new.html.erb
- app/views/froggo_teams/show.html.erb
- app/views/github_users/show.html.erb
- app/views/home/index.html.erb
- app/views/layouts/application.html.erb
- app/views/organizations/missing.html.erb
- app/views/organizations/settings.html.erb
- app/views/organizations/show.html.erb
- app/views/pull_requests/index.html.erb
- app/views/pull_requests/show.html.erb
Froggo es la aplicación web que utilizamos para coordinar la revisión de Pull Requests. 
Necesitaba un refactor porque cada vez que se hacía una vista nueva era necesario agregar:
`<div id="app" class="app">`
`<%= render 'partials/header' %>`
` .......`
`<%= render "partials/footer" %>`
`</div>`
Por lo que se agregó esto al layout en application.html.erb, se sacaron de las vistas que lo incluían y se agregó más info a Home que no utiliza el layout. Quedando el layout finalmente así:
Y todas las vistas funcionando con normalidad ✅
> refactor(application.html.erb): changed the views base to layout

- app/javascript/components/organizations-dropdown.vue
- app/javascript/components/profile-dropdowns.vue
- app/javascript/components/teams-dropdown.vue
- app/javascript/components/timespan-dropdown.vue
- app/javascript/locales/en.js
- app/javascript/locales/es.js
En la página principal de froto (el perfil), uno puede escoger por cuantos meses quiere ver, que equipo y que organización. Sin embargo los defaults se escogen por el admin de la organización. 
Ahora con localStorage cada usuario puede escoger personalizado sus defaults. Simplemente apretando el botón de "set default":
> feat(profile-dropdowns): added option to default month, team, organiz

- app/assets/stylesheets/app/card.scss
- app/javascript/components/profile-dropdowns.vue
- app/javascript/locales/es.js
En el botón Predeterminar del perfil:
Se hicieron 3 cambios:
1.- Ver cómo se ve solo si dice “Predeterminar”.
2.- Que al poner el mouse encima el fondo blanco pase a ser verde y la letra blanca para que se note que lo vas a apretar
3.- Sacarle el margin-right y dejarlo en 0 (al botón)
Quedando con hover así:
> fix(card.css): change style of button

- app/javascript/components/organizations-dropdown.vue
- app/javascript/components/profile-dropdowns.vue
- app/javascript/components/teams-dropdown.vue
- app/javascript/components/timespan-dropdown.vue
- app/javascript/locales/en.js
- app/javascript/locales/es.js
- app/javascript/store/modules/profile/actions.js
- db/schema.rb
Ahora con localStorage cada usuario puede escoger personalizado sus defaults. Simplemente apretando el botón de "set default":
No obstante, no estaban bien conectados los dropdowns con la barra de personas que se muestran abajo. Se arregló esto siguiendo la lógica ids para las personas y usando localStorage con índex para el dropdown.
Por último, se agregó un aviso al predeterminar un equipo.
> fix(profile-dropdowns.vue): fix the connection dropdowns and chart

- app/javascript/components/organizations-dropdown.vue
- app/javascript/components/teams-dropdown.vue
Ahora con localStorage cada usuario puede escoger personalizado sus defaults. Simplemente apretando el botón de "set default":
No obstante, no estaba bien conectados los dropdowns del equipo/team con la barra de personas que se muestran abajo. Se arregló esto siguiendo la lógica ya que se enviaba siempre el equipo por default de la organización y no la personal.
Aparte se hizo un watch() en team-dropdowns.vue en vez de mounted porque la información de selectedOrganizationTeams manda más de una vez
> fix(organizations-dropdowns.vue): fixed teams default profile

- app/commands/get_review_recommendations.rb
- app/javascript/components/profile/relations.vue
Se quiere poder visualizar los tags de los usuarios en la barra de relaciones haciendo hover sobre las caras.
Se agregan los tags al computar GetReviewRecommendations, además se utilizan para agregarlos al texto del hover.
> feat(hover-tags): add tags to hover in relation table

- app/models/github_user.rb
Se quiere que la descripción en el usuario sea opcional.
Se cambia la validación que permitía que la descripción fuese un string de 0 a 255 caracteres, por una que nos pide que sea sólo de máximo 255 caracteres, para poder permitir que la descripción sea opcional.
> fix(description-validator): delete description validator

- app/values/github_session.rb
En staging y producción, repentinamente, la plataforma respondía error 500 a varios usuarios.
Debuggeando en local con uno de los usuarios afectados, nos dimos cuenta que tenía que ver con la serialización muy grande de un objeto del cuál solo se necesitaba un atributo.
Se soluciona momentariamente el problema con un `to_json` custom en el objeto involucrado.
> fix(github): add custom to_json method to avoid ascii bug

- .eslintrc.json
- app/assets/stylesheets/app/profile.scss
- app/controllers/github_users_controller.rb
- app/javascript/components/pending-pr.vue
- app/javascript/packs/application.js
- app/javascript/spec/components/pending-pr.spec.js
- app/views/github_users/_profile_card.html.erb
- spec/controllers/github_users_controller_spec.rb
Froggo es un proyecto interno para hacer lo más surtida posible la corrección de *pull requests* (PR's). Creemos que los PR's son una fuerte herramienta de transmisión de conocimiento de desarrollo y formas de abordar los problemas.
La aplicación tiene una grilla por organizaciones donde se puede ver todos los PR's enviados históricamente entre personas, y posee una vista personal donde se recomienda a quiénes mandar el siguiente PR y a quiénes evitar (recomendador).
La idea es potenciar la vista personal para que los desarrolladores solo deban ingresar a esta única vista.
Ha sido mencionado varias veces que sería cómodo poder asignar un PR desde Froggo directamente. Esto evitaría estar saltando de una página a otra para asignar un PR. En cambio permitiría simplificar el flujo.
Se …
> Pending pr

- app/assets/stylesheets/app/profile.scss
- app/assets/stylesheets/app/select.scss
- app/javascript/components/clickable-dropdown/index.vue
- app/javascript/components/profile/team-tags-container.vue
- app/javascript/components/profile/team-tags-table.vue
Se busca tener una tabla inicialmente en la cual se pueda ver todos los tags de cada una de las personas del equipo y se pueda filtrar por nombre y por tags.
- Se fijó el ancho de las columnas para que estas no cambiaran al aplicar los filtros
- Se fijó el alto de los comentarios en relación al alto de los tags (si es que los hay) y que el resto se scrolle ( si es que es muy largo).
- Se le agregó un alto mínimo a la tabla (para que quepan los dropdowns cuando no queda ningun usuaario tras aplicar un filtro)
- Se cambió el select de color a formato vertical (antes era horizontal)  y se le agregó la opción de seleccionar todas. 
- Se cambió el loading icon al componente teamTagsTableContainer, porque sino en  teamTagsTable fallaban los refs para calcular el alto de la fila.
- El componente …
> Team tags table style

- app/javascript/components/profile/team-tags-table.vue
- app/javascript/helpers/color-from-score.js
Si en un equipo habían personas con score -1,  ocurría un error en el mounted, la tabla no mostraba a los miembros del equipo y el select de tags no tomaba el ancho esperado. 
Se cambió a que en la tabla de tags las personas con score -1 (esto significa que  su promedio de  PRs es 0) tengan color 'red' en vez de un string vacío, para que no fallen los filtros ni  la clases de css para los círculos de colores de la tabla.  Así no ocurre un error en las filas de los usuarios con score negativo, lo que evita el error del mounted ( que ocurría al no encontrar refs de esos usuarios).  
- El helper colorFromScore, al que se le agregó el argumento noColor. Se dejó como valor default un string vacío (que era lo que retornaba antes) para no afectar los llamados a la función en otros lados.
- El …
> fix(team-tags-table/colorFromScore): Show red for -1 scores in table

- app/commands/get_review_recommendations.rb
- app/javascript/components/profile/relations.vue
Ordenar las recomendaciones con un segundo criterio: última fecha de corrección de PR. Además, incluir el valor del puntajes y la última revisión de un usuario al hacer hover.
- Froggo ayuda a seleccionar a quién enviarle un PR.
- Actualmente estamos enfocados en perfeccionar esto.
- Se agrega para cada usuario la última fecha a la cuál le revisó un PR al usuario actual.
- Se agrega un segundo criterio al `sorted_by` para ordenar por la última fecha de revisión si esque el `:score` es el mismo.
- Se elimina los tags del hover porque existe un tabla para esto
- Se elimina código que no se utilizaba y que llamaba a métodos o properties que no existen.
Así se veía antes:
Así está ahora:
Nótese que en la segunda foto cambió el orden y eso es porque se está ordenando también por la última …
> Second criteria to sort recomendations

- app/controllers/organizations_controller.rb
- spec/controllers/organizations_controller_spec.rb
Redirigir al usuario para que autorice la app en caso de que sea admin en Github y tenga permiso de :member en las cookies.
- Froggo se utiliza para recomendar a quién enviar tu próximo PR.
- En Froggo se utiliza OAuth de Github para generar un `access_token`.
- Todos ingresamos con un `access_token` con un scope de `:member`, es decir, que podemos hacer pocas cosas.
- Cuando eres :admin en Github de un repositorio y quieres configurarlo en Froggo, se te pidirá volver a generar este `access_token` para crearlo con permiso de `:admin`.
> Setting view

- Gemfile.lock
- app/javascript/api/froggo_teams.js
- app/javascript/api/index.js
- app/javascript/api/organizations.js
- app/javascript/api/pull_request_reviewers.js
- app/javascript/api/pull_requests.js
- app/javascript/api/repositories.js
- app/javascript/api/users.js
- app/javascript/components/dashboard-syncing-icon.vue
- app/javascript/components/froggo-team-edit.vue
- app/javascript/components/froggo-team-show.vue
- app/javascript/components/open-pr.vue
- app/javascript/components/pr-feed.vue
- app/javascript/components/pr-show.vue
- app/javascript/components/profile-description.vue
- app/javascript/components/profile/recommendations-users.vue
- app/javascript/components/profile/relations.vue
- app/javascript/components/profile/team-tags-table.vue
- app/javascript/components/repository.vue
- app/javascript/components/sync-organization-button.vue
- app/javascript/components/user-tags.vue
- app/javascript/locales/es.js
- app/javascript/store/modules/admin/actions.js
- app/javascript/store/modules/froggo_team/actions.js
- app/javascript/store/modules/profile/actions.js
- app/views/froggo_teams/edit.html.erb
- app/views/froggo_teams/show.html.erb
- app/views/github_users/_profile_card.html.erb
Queremos todas las llamadas a la API desde uno o varios archivos.
Se crea el `index.js` con el método api que se usará en las llamadas (copiado directamente de [Mute](https://github.com/platanus/mute-meetings/blob/development/app/javascript/api/index.js))
Se crean los archivos para cada categoría de llamada a la api.
Se reemplazan las llamadas en los componentes y actions por los métodos de los archivos nuevos.
Se camelizan los props de users que se pasan en vistas rails para que sea consistente con los responses de la api de users.
Que no se me haya pasado algún prop que haya dejado de funcionar por no estar camelizado :grimacing:
> Centralize api calls

- app/assets/stylesheets/app/card.scss
- app/commands/github/process_membership_event.rb
- app/controllers/github_auth_controller.rb
- app/controllers/organizations_controller.rb
- app/views/organizations/_admin_permission.html.erb
- app/views/organizations/_init.html.erb
- app/views/organizations/settings.html.erb
- spec/commands/github/process_membership_event_spec.rb
- spec/controllers/github_auth_controller_spec.rb
- spec/controllers/organizations_controller_spec.rb
Incorporar nuevamente la creación de una Organización en Froggo ya que la borré por accidente en un PR anterior.
Crear la instancia de la relación entre organización y usuario (`OrganizationMembership`) en el webhook y al momento de crear un usuario.
- Froggo se utiliza para recomendar a quién enviar tu próximo PR.
- Estamos volviendo a las bases y mejorando el onboarding y usabilidad.
- Al agregar un usuario en Github el webhook intentará crear una relación con la orgnización si no está creada.
- El método `callback` de `GithubAuthController` es al que llama Github después de autentificar a un usuario. En este método ahora se intentará crear la relación con todas las organizaciones en Froggo que pertenezca el usuario en Github.
- Se corrigió un error que cometí al borrar algunas cosas en …
> Find or create user when added to GitHub

- .postcssrc.yml
- app/assets/stylesheets/app/_base.scss
- app/javascript/packs/application.js
- app/views/layouts/application.html.erb
- tailwind.config.js
Dejar habilitado tailwind para desarrollo.
- Froggo se utiliza para recomendar a quién enviar tu próximo PR.
- Se eliminó el archivo `postcssrc.yml` ya que ahora se utiliza `postcss.config.js`.
- Se movió la carga de font para que se el head. Esto resuelve el problema de distintos fonts en desarrollo y en producción.
- Se incluye el css a vue para que tailwind funcione.
- Se agrega una configuración básica de tailwind.
> Enable tailwind

- app/controllers/api/v1/github_users_controller.rb
- app/controllers/api/v1/organizations_controller.rb
- config/routes.rb
Estoy trabajando en la extensión de Chrome para Froggo y hay un par de endpoints que me faltan de API
Se agregan los siguientes endpoints
- Obtener las organizaciones del usuario logueado
- Obtener los prs abiertos del usuario logueado
> Froggo ext endpoints

- app/models/preference.rb
- app/models/user.rb
- db/migrate/20210602150223_create_preferences.rb
- db/schema.rb
- spec/factories/preferences.rb
- spec/models/preference_spec.rb
En Froggo, actualmente las preferencias del usuario se guardan en el storage del navegador. Si un usuario cambia de navegador o usa la nueva extensión, las preferencias desaparecen por no estar guardadas en el backend.
-  Se crea el modelo `Preference`, que contiene las preferencias de un usuario para una organización (`default_organization_id`), equipo (`default_team_id`) y el tiempo (`default_time`) con un enum para determinar los tiempos disponibles.
- Se agregan los tests de validación y relación.
> Create Preference model

- app/models/github_user.rb
- app/models/preference.rb
- app/models/user.rb
- db/migrate/20210614120524_remove_user_id_from_preferences.rb
- db/migrate/20210614121057_add_github_user_reference_to_preferences.rb
- db/schema.rb
- spec/factories/preferences.rb
- spec/models/github_user_spec.rb
- spec/models/preference_spec.rb
En #384 se creó una relación entre el modelo `Preference` y el modelo `User`, cuando lo correcto tendría que haber sido asociarlo con el modelo `GithubUser`
- Se elimina la columna `user_id` de la tabla `preferences` y se agrega una columna `github_user_id`
- Se elimina la relación del modelo `User` y se agrega al modelo `GithubUser`. También se corrige en el modelo `Preference`
- Se corrigen los tests
- *Bonus Track*: Se reemplaza `should` por `is_expected.to` en los tests de `GithubUser`
> Fix: Associate Preferences with GithubUser instead of User

- app/javascript/components/profile/relations.vue
Formatear la última revisión desde el backend.
En la imagen se ve que la fecha no se está mostrando:
Con este cambio debería mostrarse sin problemas.
> feat(review-recomendation): add format to last_review from backend

- app/controllers/api/v1/preferences_controller.rb
En los PRs anteriores se movieron las preferencias de usuario al backend, a las que se puede acceder via api.
Como es posible que los usuarios antiguos no tengan sus preferencias guardadas en el backend, cuando se llame a la api (tanto en show como update), si no existe una `preference` para ese `github_user`, se crea una con valores por defecto.
> create default preference on api call

- app/controllers/api/v1/preferences_controller.rb
- app/serializers/api/v1/preference_serializer.rb
Al llamar a la api de preferences, si no existe una `preference` para el usuario, se crea una con valores por defecto. Los valores por defecto incluían el id de la primera organización a la que pertenezca el usuario, y lo mismo para el froggo team, pero no contemplaban el caso en que el usuario se haya creado recién y no pertenezca a ninguna org ni team.
- Si el `GithubUser` no pertenece a una `Organization`, la `preference` se crea con `org_id = nil` (análogo para `FroggoTeam`)
- En vez de mostrar el `org_id` y `team_id`, se serializan la `organization` con esa id, y lo mismo para el `froggo_team`, por conveniencia a la hora de hacer cosas en el frontend.
> Preference API fixes

- app/models/assignation_metric.rb
- app/models/github_user.rb
- app/models/pull_request.rb
- db/migrate/20210714212330_create_assignation_metrics.rb
- db/schema.rb
- spec/factories/assignation_metrics.rb
- spec/models/assignation_metric_spec.rb
- spec/models/github_user_spec.rb
- spec/models/pull_request_spec.rb
El modelo `assignationMetric` trackea las asignaciones de una pr a un usuario tanto a traves de la pagina, como de la extension.
- Se agrega el modelo `AssignationMetric`, y sus relaciones con `PullRequest` y `GithubUser`, con un campo `from` que puede ser "desktop" o "extension".
- Se agregan los tests de validación y relación.
> assignationMetric Model

- app/javascript/components/recommendations/team-relations.vue
- app/javascript/components/recommendations/team-table.vue
- app/javascript/components/recommendations/team.vue
- app/javascript/components/relation.vue
- app/javascript/helpers/tailwind-color-from-score.js
En #395 se incluyo un helper de clases de tailwind para aplicar algunos colores en la vista de recomendaciones, pero se aplicaban en runtime, y no pasaban el purge.
- El helper ahora devuelve la clase completa `bg-color-123`
- Las tablas de recomendaciones ahora _calculan_ el color directamente
> fix: recommendations view color helper

- app/assets/images/check.svg
- app/assets/images/content-copy.svg
- app/controllers/recommendations_controller.rb
- app/javascript/components/recommendations/index.vue
- app/javascript/components/recommendations/multiselect-reviewer.vue
- app/javascript/components/recommendations/open-pr.vue
- app/javascript/components/recommendations/open-prs.vue
- app/javascript/components/recommendations/team.vue
- app/javascript/locales/en.js
- app/javascript/locales/es.js
- app/serializers/pull_request_serializer.rb
- app/views/recommendations/show.html.erb
- package.json
- yarn.lock
El rediseño de la página de recomendaciones de Froggo incluye las prs abiertas, sus revisores asignados, y la posibilidad de asignar un revisor a cada pr.
https://www.figma.com/file/ZZvsjJJIkiHhX8NRVxRuXV/Froggo?node-id=598%3A11
- Se agregan los componentes `open_pr`, `open_prs` y `multiselect-reviewer`, a la vista de recomendaciones
- La funcion `serialized_open_prs` de `recommendations_controller`. La estructura de `open_prs` es:
[ 
{
pull_request: PullRequest, 
reviewers: [GithubUser, ...] 
}, ...
]
Existe otra forma de aplicar el serializer que corresponde a cada modelo `PullRequest` y `GithubUser` dentro de `open_prs`?
-----------
> PRs abiertas en vista de recomendaciones

- app/javascript/components/recommendations/open-pr.vue
- app/javascript/components/recommendations/team-relations.vue
En Froggo estamos desarrollando la nueva pagina de recomendaciones:
https://www.figma.com/file/ZZvsjJJIkiHhX8NRVxRuXV/Froggo?node-id=598%3A11
Con la ultima pr quedaron dos bugs que esta pr soluciona:
- Si una pr tiene muchos reviewers, las fotos de los reviewers se _achican_ para caber en el espacio.
- Los tooltip de los _circulitos de colores_  en `team-relations` no funcionan.
- Se permite que el espacio que ocupan las fotos de los reviewers de una pr pueda agrandarse (`flex-grow`), y ocupar espacio que normalmente ocuparia el titulo de la pr.
- El bug de los tooltip encima de los _circulitos de colores_ en `team_relations`, esta parcialmente solucionado. El problema viene de incluir `v-tooltip` dentro de `vue-horizontal`, y solucionarlo implica probablemente reescribir la libreria.
> Fix tooltips and space for reviewers in recommendations view

- app/controllers/api/v1/pull_request_reviewers_controller.rb
- app/javascript/components/recommendations/multiselect-reviewer.vue
- app/javascript/components/recommendations/open-pr.vue
- app/models/assignation_metric.rb
- app/views/recommendations/show.html.erb
- db/migrate/20210820142240_remove_unique_index_from_assignation_metric.rb
- db/schema.rb
- spec/models/assignation_metric_spec.rb
En Froggo queremos medir cuanto se usa la plataforma y para eso implementamos el modelo AssignationMetric, el cual se creaba una vez por cada persona que asigno a una PR. Esto resultó no ser tan util, ya que asignar a 5 personas a una misma PR podia inflar las métricas, asi que decidimos medir cuantas veces se usa la plataforma, o cuantas veces se hace click en "asignar". Para eso se tuvo que implementar el poder asignar varios revisores "de una sola vez"  a una pr.
- El endpoint para asignar revisores soporta un arreglo de usuarios para asignarlos todos de una vez.
- El modelo AssignationMetric relaciona el usuario de Froggo con una Pr.
- Se soluciona un pequeño bug que no mostraba las imagenes de los asignados, con `camelizeKeys`
> Assign multiple reviewers at once

- app/controllers/api/v1/pull_request_reviewers_controller.rb
- config/routes.rb
Corregir un bug. Se estaba intentando buscar un usuario a partir del `login`, pero se estaba recibiendo el objeto del usuario así que agregué un `reviewer.login` para corregir el problema.
Además cambié el `root` de las rutas para que lleve a las recomendaciones.
> Fix pr assign

- app/javascript/components/profile-description.vue
Se está haciendo un rediseño de la vista de perfil de usuario en Froggo. Uno de los cambios es en la descripción del usuario, la cual se puede editar, y para guardar los cambios se usa un botón guardar.
Antes el botón guardar desaparecía cuando no había cambios que guardar en la descripción.
Ahora el botón no desaparece, solo se deshabilita cuando no hay cambios que guardar.
---
Botón desactivado:
Botón activado:
> refactor(profile/desciption): change button behaviour when disabled

- app/controllers/github_users_controller.rb
- app/javascript/components/profile-card.vue
- app/javascript/components/profile/teams.vue
- app/javascript/locales/es.js
Se cambió el diseño de la vista de perfil de usuarios según [este Figma](https://www.figma.com/file/ZZvsjJJIkiHhX8NRVxRuXV/Froggo?node-id=508%3A2). Uno de los requerimientos era que los otros usuarios pudieran ver la vista de perfil de otros usuarios, pero no editarla.
- Se arregla la obtención de los equipos del usuario en el controlador, lo que permite que ahora se pueda ver el perfil de otros usuarios. Además se elimina código no usado.
- Se arregla detalle de los mensajes en la vista del perfil
---
Vista del propio usuario:
Vista de otro usuario:
> fix(github_user): fix show view of other users

- app/javascript/components/profile/teams.vue
En Froggo se está renovando el diseño de la vista del perfil de usuario. Una nueva funcionalidad que se agregó es la de mostrar los equipos del usuario, junto con la posibilidad de que se active o desactive de esos equipos. Además, se incluyó un botón "desactivarme en todos", para facilitar la desactivación de un usuario de sus equipos.
El problema es que una vez que se desactivan todos los equipos, el usuario tiene que volver a activarlos uno a uno. Por eso, cuando todos los equipos estén desactivados, se necesita un botón para volver a activarlos todos.
- Se cambia el botón para incluir la opción "activarme en todos" cuando los equipos estén desactivados
---
Video funcionamiento:
https://user-images.githubusercontent.com/42162243/143584894-10d3923d-5cad-471b-9ca6-29e8610fd970.mov
> feat(profile/teams): add activate all button

- app/controllers/api/v1/github_users_controller.rb
- app/models/pull_request.rb
- app/serializers/api/v1/pull_request_serializer.rb
En la extensión de Froggo se quiere separar PRs por organización, pero actualmente no se puede obtener la organización de un PR.
- Se agrega `organization_id` al serializer de `PullRequest`
- Se serializan los PRs en la llamada a `open_prs`
> Send organization_id on PR api

- app/serializers/api/v1/pull_request_serializer.rb
En el PR anterior se cambió el serializer que se usaba `open_prs`, pero quedó fuera este atributo
- Se agrega el atributo `gh_number` a `PullRequestSerializer`
> F/add PR number to PR api serializer
