platanus/froggo

app/clients/octokit_client.rb
app/models/hook.rb
app/observers/repository_observer.rb
app/services/github_service.rb
app/workers/github_worker.rb
db/schema.rb
scripts/pull_requests.rb
spec/observers/repository_observer_spec.rb
spec/services/github_service_spec.rb
spec/workers/github_worker_spec.rb

Add method to github service and corresponding test.

Pull requests tracked repo

---

app/admin/dashboard.rb
app/models/admin_user.rb
config/locales/en.yml
config/locales/es-CL.yml

Add reset token button, and move both the reset and the auth button to `page_actions`.

feat(Token): Add reset token button

---

.eslintrc.json
.gitignore
.hound.yml
app/javascript/pl-dropdown.vue
app/javascript/repository.vue
app/javascript/sync-organization-button.vue
package.json
yarn.lock

Se agregó linter de vue y se arreglaron los problemas de estilo en los componentes.

chore(vue-components): add vue linter and fix style issues

---

app/assets/stylesheets/app/home.scss
app/views/home/index.html.erb
config/locales/en.yml
config/locales/es-CL.yml

- Se removieron los lorem ipsum del home
- Se mejoró la descripción del dashboard

fix(): change home texts and remove lorem ipsum

---

app/controllers/organizations_controller.rb
app/values/correlation_matrix.rb
spec/values/correlation_matrix_spec.rb

Ahora el usuario logrado aparecerá en el primer lugar de la matriz.
- Se creó el método `place_current_user` que posiciona al usuario loggeado en la primera posición.

Current user first

---

app/assets/stylesheets/app/dashboard.scss

fix(): increase width

---

yarn.lock

😨 heroku no buildea porque estaba instalando con npm
Aquí va el `yarn.lock` actualizado.

fix(yarn): update yarn.lock

---

app/views/home/index.html.erb

El botón de login que está en home tenía mal puesto el link.

fix(login-button): fix login button redirect url

---

app/services/github_pull_request_service.rb
spec/services/github_pull_request_service_spec.rb

Se estaban guardando los `requested reviewers` solo si estos se seleccionaban antes de crear el PR, y no se estaba guardando el `id` del reviewer. Ahora los `requested reviewers` se guardan independientemente del momento en que son solicitados, se asegura que no se guarde más de una vez el mismo reviewer para un PR, y los `id` se guardan correctamente.

fix(user-statistics): fix pull request reviews requested creation

---

app/services/github_pull_request_service.rb
spec/services/github_pull_request_service_spec.rb

Los `requested_reviewers` de un PR se estaban intentando obtener dentro del field `pull_request` del payload de la API de Github. Se arregla eso para obtenerlos del field `requested_reviewers` del payload.
- Se intenta agregar `requested_reviewers` al PR solo si existe ese field en el payload.
- Cambios en los tests para reflejar el cambio en la lógica.

fix(requested-reviewers): fix PR requested reviewers creation

---

app/controllers/api/v1/froggo_teams_controller.rb
app/models/froggo_team.rb
app/models/froggo_team_membership.rb
app/models/github_user.rb
app/models/organization.rb
app/responders/api_responder.rb
app/serializers/froggo_team_serializer.rb
config/routes.rb
db/migrate/20200812192457_create_froggo_teams.rb
db/migrate/20200812192740_create_froggo_team_memberships.rb
db/migrate/20200813155456_add_organization_to_froggo_team.rb
db/schema.rb
spec/controllers/api/v1/froggo_teams_controller_spec.rb
spec/factories/froggo_team_memberships.rb
spec/factories/froggo_teams.rb
spec/models/froggo_team_membership_spec.rb
spec/models/froggo_team_spec.rb

En este PR están los commits de la creación de los modelos, controladores, serializadores y cosas básicas para definir los equipos locales de froggo :) Solo back-end.

Froggo local teams

---

app/commands/get_user_review_request_metrics.rb
spec/commands/get_user_review_request_metrics_spec.rb

PR para arreglar el formato de la respuesta de la api al llamar el método pull_requests_information

fix(user-metrics): Fix structure for pull_requests_information response

---

app/assets/stylesheets/app/card.scss
app/controllers/api/v1/likes_controller.rb
app/controllers/pull_requests_controller.rb
app/javascript/components/pr-feed.vue
app/models/github_user.rb
app/models/like.rb
app/models/pull_request.rb
app/serializers/pull_request_serializer.rb
app/views/partials/_header.html.erb
app/views/pull_requests/index.html.erb
config/locales/es-CL.yml
config/routes.rb
db/migrate/20200819190918_create_likes.rb
db/schema.rb
spec/controllers/api/v1/likes_controller_spec.rb
spec/controllers/pull_requests_controller_spec.rb
spec/factories/likes.rb
spec/models/like_spec.rb

en esta branch se agrega el modelo de Like que relaciona un usuario con un polimórfico, en este caso un pull request. Además se agrega el controlador en la API para que desde el componente feed.vue se pueda hacer like a los pull requests.

feat(likes_controller.rb): add like model and like function

---

app/assets/stylesheets/app/profile.scss
app/controllers/api/v1/github_users_controller.rb
app/javascript/components/profile-dropdowns.vue

Este PR es para arreglar un bug cuando se hace find!() en vez de find() y aproveche de hacer un pequeño cambio de diseño

fix Froggo teams integration bug and add style

---

app/javascript/locales/en.js
app/javascript/locales/es.js

PR para agregar la coma que se perdió al resolver el conflicto para mergear

fix(javascript/locales) fix expected token

---

app/assets/stylesheets/app/card.scss
app/controllers/pull_requests_controller.rb
app/javascript/components/pr-feed.vue
app/javascript/components/pr-show.vue
app/javascript/locales/en.js
app/javascript/locales/es.js
app/javascript/packs/application.js
app/models/pull_request.rb
app/models/pull_request_review.rb
app/serializers/pull_request_review_serializer.rb
app/serializers/pull_request_serializer.rb
app/views/pull_requests/index.html.erb
app/views/pull_requests/show.html.erb

En este PR en Froggo, se continuó trabajando en las Pull Requests que se presentan en el Feed de Froggo, funcionalidad que se agregó hace poco para poder likear las PR donde más se pueda aprender de buenas prácticas, formas de trabajar en Platanus, etc.
Ahora se agregó la vista de la PR con más información que se puede acceder desde el Feed con el botón Ver:
Y se hizo un show de las PR con una vista bastante rústica, a la cual se le piensa agregar más diseño en la próxima PR:

Pr details

---

app/assets/stylesheets/app/card.scss
app/javascript/components/pr-feed.vue
app/javascript/components/pr-show.vue
app/javascript/locales/en.js
app/javascript/locales/es.js
app/models/pull_request.rb

Se mantuvo toda la información y solo se buscó cambiar el diseño y distribución en las vistas de pr-feed y pr-show.
Quedó finalmente de la siguiente manera:
Feed:
Show:

feat(pr-feed.vue and pr-show.vue): added design and better distribution

---

Gemfile
Gemfile.lock
app/assets/stylesheets/app/card.scss
app/controllers/pull_requests_controller.rb
app/views/kaminari/_first_page.html.erb
app/views/kaminari/_gap.html.erb
app/views/kaminari/_last_page.html.erb
app/views/kaminari/_next_page.html.erb
app/views/kaminari/_page.html.erb
app/views/kaminari/_paginator.html.erb
app/views/kaminari/_prev_page.html.erb
app/views/pull_requests/index.html.erb
config/initializers/kaminari_config.rb

Contexto:
Froggo es donde coordinamos las revisiones de PR. Actualmente se está trabajando en el Feed que es un lugar donde se pueden ver todas las PRs hecha para revisarlas y darle like si encuentras que se puede aprender de esa PR
Cambios:
antes se mandaban las últimas 100, ahora se envían todas pero con paginación. Lo que se hizo fueron tres cosas:
- agregar la gema kamirimi
- permitir la paginación de las PR
- agregar un poco de diseño a la barra de navegación (se crearon como 6 archivos únicamente para esto, se piensa hacer más trabajo en ellas más adelante)

feat(pull_requests_controller): added pagination with kaminari gem

---

app/assets/stylesheets/app/app.scss
app/assets/stylesheets/app/dropdown.scss
app/assets/stylesheets/app/froggo_teams.scss
app/javascript/components/froggo-team-edit.vue
app/javascript/components/froggo-team-show.vue
app/javascript/components/percentage-dropdown.vue
app/javascript/locales/en.js
app/javascript/locales/es.js
app/javascript/packs/application.js

En este PR se crea el componente de vue percentage-dropdown y se añade a la vista de los equipos de froggoTeams.
La idea es que el usuario de un FroggoTeam pueda decidir qué porcentaje de asignación de PRs le gustaría tener en el equipo.
Aquí una foto del antes y el después :)

Percentage dropdown

---

app/assets/stylesheets/app/card.scss
app/commands/filter_pull_requests.rb
app/views/pull_requests/index.html.erb

El feed se presentan todas las pull requests que hay en platanus. Esto claramente es un problema por las decenas que se hacen diarias y se dificulta la búsqueda de un PR en específico. Para esto se decidió hacer filtros.
Son 6 filtros que se veían así:
Y ahora se ve así:

design(index.html.erb): change design of filter pr

---

app/assets/stylesheets/app/app.scss
app/assets/stylesheets/app/profile.scss
app/assets/stylesheets/app/profile_description.scss
app/controllers/api/v1/github_users_controller.rb
app/javascript/components/profile-description.vue
app/javascript/packs/application.js
app/models/github_user.rb
app/services/github_user_service.rb
app/views/github_users/_profile_card.html.erb
config/routes.rb
db/migrate/20201222181227_add_description_to_github_user.rb
db/schema.rb
spec/factories/github_users.rb
spec/services/github_pull_request_review_service_spec.rb
spec/services/github_user_service_spec.rb

Cuando se va al perfil de una persona en froggo se debe ver una descripción de esta, si me encuentro en mi propio perfil y no cuento con una descripción debo poder crearla, si ya tengo una, se debe poder editar haciendo doble click sobre esta.
Se agrega un atributo descripción al github user, además de la ruta api/github_users/:id/update_description, la cual es utilizada en el componente user-read-more.vue, que se encarga de visualizar, crear y editar la descripción del usuario.

Feat description

---

app/assets/stylesheets/app/profile_description.scss
app/assets/stylesheets/app/tags-show.scss
app/assets/stylesheets/app/user_tags.scss
app/javascript/components/profile-description.vue

El modal para agregar tags tenía algunos estilos que no concordaban con el estilo del resto de la página.
Se cambiaron algunos estilos de fuentes, colores, etc.

fix(style): change font ans size of text

---

app/assets/stylesheets/app/profile.scss
app/assets/stylesheets/app/select.scss
app/javascript/components/clickable-dropdown/index.vue
app/javascript/components/profile/team-tags-container.vue
app/javascript/components/profile/team-tags-table.vue
app/javascript/components/profile/team-tags.vue
app/javascript/locales/en.js
app/javascript/locales/es.js
app/javascript/packs/application.js
app/views/github_users/_profile_card.html.erb

Se busca tener una tabla inicialmente en la cual se pueda ver todos los tags de cada una de las personas del equipo y se pueda filtrar por nombre y por tags.
Se agregó una tabla con los usuarios de un equipo, con una columna de color, tag y descripción. Los selects para los filtros están pero no funcionales.
- Los nuevos componentes d vue: TeamTags, TeamsTagsTable y TeamTagsContainer
- El archivo index del sleect ClickableSelect, al que se le agregaron modos para mostrar colores, cambiar el ancho y centrar.
- Los css de profile y del select 
Link del pitch:  https://www.notion.so/platanus/Tags-3-99a5043d5aef4e69aa9a51ce7a820795
https://user-images.githubusercontent.com/30674444/107081215-1bf81100-67d1-11eb-8fba-7c8edff7a4fa.mov

Tags table

---

app/assets/stylesheets/app/profile.scss
app/controllers/api/v1/pull_request_reviewers_controller.rb
app/javascript/api/pull_request_reviewers.js
app/javascript/components/open-pr.vue
app/views/github_users/_profile_card.html.erb
config/routes.rb

Se busca poder asignar revisores a pull requests abiertos.
- Se crea servicio _AddReviewerToPullRequestService_. Este llama a la API de Github para agregar un nuevo revisor a un PR.
- Se crea _PullRequestReviewersController_ : Controlador que recibe la información del PR y del revisor que se quiere asignar, y llama al servicio mencionado anteriormente.
- _open-pr.vue_ editado para tener el id del PR, además del título.
- ¿Está bien que sea un servicio, o debería ser un command?
- ¿Es correcta la forma en que se envía la información desde vue hasta rails (usando axios para hacer un post)?
- ¿El test del _Service_ debería testear algo más?
- ¿El manejo de errores es suficiente?

Add prs reviewer

---

app/assets/stylesheets/app/profile.scss
app/javascript/components/open-pr.vue

Cambiar algunos detalles de como se verá la asignación de prs desde froggo.

feat(open-pr): change css properties

---

app/commands/get_review_recommendations.rb
app/javascript/components/profile/relations.vue

- Incluir fecha lejana cuando el usuario nunca le ha corregido un PR.

Hot fix 12/03/2021

---

app/views/layouts/application.html.erb
app/views/partials/_heap.html.erb

Agregar [Heap](https://heap.io/) a Froggo.
- Sea agrega una variable de ambiente para el ID.

feat(heap): add heap call

---

app/javascript/components/profile/metrics-handler.vue
app/javascript/store/modules/profile/mutations.js

Actualizar la métricas temporales para utilizar camel case.
- Froggo se utiliza para recomendar a quién enviar tu próximo PR.
- En este PR #359 se centralizó las llamdas a la API y se implementó camel case para todo los atributos de los objetos que entran a la API.
- Acá aplico camel case para algunos que faltó implementar.

Not camel case errors

---

app/views/layouts/application.html.erb

Corregir error de compilación en staging/producción.
Se agrega el `stylesheet_pack_tag` para resolver el problema.

feat(application): add pack_tag to application.html.erb

---

app/assets/stylesheets/app/profile.scss

Corregir posición de ciculo sobre recomendación.
1. Así estaba:
2. Así quedó:

fix(profile): color circle position

---

app/javascript/components/open-pr.vue

Agregar una clase para que Heap Analytics lo detecte.

feat(open-pr): add class for heap analytics detection

---

app/javascript/components/open-pr.vue

Agregar una clase para que Heap Analytics lo detecte.

Paso a producción 28/05

---

app/javascript/api/preferences.js

En Froggo, actualmente las preferencias del usuario se guardan en el storage del navegador. Si un usuario cambia de navegador o usa la nueva extensión, las preferencias desaparecen por no estar guardadas en el backend.
Ya están los endpoints de la api expuestos para obtener y cambiar las preferencias del usuario, falta conectarlas con el frontend.
- Se crea el archivo `preferences.js` con los métodos para llamar a la api de preferences.

feat(api): add preferences api methods

---

app/javascript/components/recommendations/dropdown-teams.vue
app/javascript/components/recommendations/dropdown-timespan.vue
app/javascript/components/shared/dropdown-organization.vue

Los items del dropdown de organizaciones de header no cambian el icono del mouse al ponerlo encima.
- Se agrega la clase `cursor-pointer`

Fix: navbar dropdown cursor

---

app/controllers/api/v1/pull_request_reviewers_controller.rb

El modelo `assignationMetric` trackea las asignaciones de una pr a un usuario tanto a traves de la pagina, como de la extension. 
- Se crea una instancia de `assignationMetric` al momento de acceder al endpoint `add_reviewer`. 
- Se dividió la funcion `request_reviewer` en otras mas pequeñas para que pase el limite de 15 lineas.

Create assignationMetric on add_reviewer

---

.buildpacks
Gemfile
Procfile
bin/release

- Agregar un archivo _release_.
- Sacar multipack viejo.
- Mover spring a developer.

Chore updates

---

app/controllers/organizations_controller.rb
app/javascript/components/profile/teams.vue
app/views/organizations/_card_header.html.erb
config/locales/es-CL.yml

- Agregar un botón para poder crear una organización si esque no está creada a nivel de base de datos.

Paso a prodcucción 03/01/2022
